### ISSUE TITLE
Create and apply tests for edge cases

### ISSUE THREAD

**Issue by lukefranc0** [CSC4790-Fall2024-Org/Grocery-Receipt-App#28]

**Comment by JadenBresciaVillanova** [comment]
**Test Case Ideas:**
_Item Amount Variation_
- 1 Item on Receipt + Test Multiple Stores (if possible)
- 1-20 Item Receipts + Test Multiple Stores (if possible)
- 20+ Item Receipts + Test Multiple Stores (if possible)
_Camera Distance_
- Take a photo of a receipt 1" away
- Take a photo of receipt 2" away
- Take a photo of receipt 3"+ away
_Lighting Variations_
- Take a photo of receipt in dimly lit room
- Take a photo of receipt in super bright room
_Receipt Orientations_
- Turn the receipt slightly sideways
- Turn the receipt upside down
_Capture Scope_
- Leave out 1-5 items on receipt
- Leave out total, subtotal, and tax (if found on receipt)
